#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KillerClient.Resource", IsApplication=true)]

namespace KillerClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_settings_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_settings_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconKiller = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int IdText = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int NameText = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int Reload = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int btnSave = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int btnSettings = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int lblPin = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int lblPort = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int lblServer = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int listProcessus = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int lstItemProcess = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int pin = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int port = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int server = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int swipeLayout = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textView2 = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Config = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProcessListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int ListProcessId = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int ListProcessName = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Pin = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Port = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int Reload = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Save = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int Server = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int server_preferences = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int summary_server = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
