//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientConsole.KillerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessusModel", Namespace="http://schemas.datacontract.org/2004/07/ProcessusKillerService")]
    [System.SerializableAttribute()]
    public partial class ProcessusModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainWindowTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainWindowTitle {
            get {
                return this.MainWindowTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MainWindowTitleField, value) != true)) {
                    this.MainWindowTitleField = value;
                    this.RaisePropertyChanged("MainWindowTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KillerServiceReference.IKillerService")]
    public interface IKillerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/GetProcessus", ReplyAction="http://tempuri.org/IKillerService/GetProcessusResponse")]
        ServiceClientConsole.KillerServiceReference.ProcessusModel[] GetProcessus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/GetProcessus", ReplyAction="http://tempuri.org/IKillerService/GetProcessusResponse")]
        System.Threading.Tasks.Task<ServiceClientConsole.KillerServiceReference.ProcessusModel[]> GetProcessusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/GetProcessusByName", ReplyAction="http://tempuri.org/IKillerService/GetProcessusByNameResponse")]
        ServiceClientConsole.KillerServiceReference.ProcessusModel[] GetProcessusByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/GetProcessusByName", ReplyAction="http://tempuri.org/IKillerService/GetProcessusByNameResponse")]
        System.Threading.Tasks.Task<ServiceClientConsole.KillerServiceReference.ProcessusModel[]> GetProcessusByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/StopProcessusByName", ReplyAction="http://tempuri.org/IKillerService/StopProcessusByNameResponse")]
        bool StopProcessusByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/StopProcessusByName", ReplyAction="http://tempuri.org/IKillerService/StopProcessusByNameResponse")]
        System.Threading.Tasks.Task<bool> StopProcessusByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/StopProcessusById", ReplyAction="http://tempuri.org/IKillerService/StopProcessusByIdResponse")]
        bool StopProcessusById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKillerService/StopProcessusById", ReplyAction="http://tempuri.org/IKillerService/StopProcessusByIdResponse")]
        System.Threading.Tasks.Task<bool> StopProcessusByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKillerServiceChannel : ServiceClientConsole.KillerServiceReference.IKillerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KillerServiceClient : System.ServiceModel.ClientBase<ServiceClientConsole.KillerServiceReference.IKillerService>, ServiceClientConsole.KillerServiceReference.IKillerService {
        
        public KillerServiceClient() {
        }
        
        public KillerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KillerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KillerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KillerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceClientConsole.KillerServiceReference.ProcessusModel[] GetProcessus() {
            return base.Channel.GetProcessus();
        }
        
        public System.Threading.Tasks.Task<ServiceClientConsole.KillerServiceReference.ProcessusModel[]> GetProcessusAsync() {
            return base.Channel.GetProcessusAsync();
        }
        
        public ServiceClientConsole.KillerServiceReference.ProcessusModel[] GetProcessusByName(string name) {
            return base.Channel.GetProcessusByName(name);
        }
        
        public System.Threading.Tasks.Task<ServiceClientConsole.KillerServiceReference.ProcessusModel[]> GetProcessusByNameAsync(string name) {
            return base.Channel.GetProcessusByNameAsync(name);
        }
        
        public bool StopProcessusByName(string name) {
            return base.Channel.StopProcessusByName(name);
        }
        
        public System.Threading.Tasks.Task<bool> StopProcessusByNameAsync(string name) {
            return base.Channel.StopProcessusByNameAsync(name);
        }
        
        public bool StopProcessusById(int id) {
            return base.Channel.StopProcessusById(id);
        }
        
        public System.Threading.Tasks.Task<bool> StopProcessusByIdAsync(int id) {
            return base.Channel.StopProcessusByIdAsync(id);
        }
    }
}
